kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  when:
    branch:
    - master
  commands:
  - cd /mnt/worldview
  - git pull
  - yarn
  - yarn build
